name: Checks

on:
  push:
    branches: [expo]
  pull_request: {}

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

defaults:
  tools:
    node: 22
    bun: 1.3.14

jobs:
  lint:
    name: Lint
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run: bun run lint

  typecheck:
    name: Typecheck
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run: bun run typecheck
